# Setup
title:        MZCL.TK
tagline:      Welcome to MZCL.TK
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Maziar
  url:        http://mzcl.tk

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
