# Setup
title:        MaziaraA.Net
tagline:      Welcome to MaziarA.Net
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Maziar
  url:        https://maziara.net

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
